<footer>
    <a href="http://www.octo.com/oss.html">
        <img src="http://www.octo.com/images/logo1.gif" height="30" alt="octo technology logo"/>
    </a>


    <a href="http://sourceforge.net/projects/jcaptcha">
        <img src="http://sourceforge.net/sflogo.php?group_id=72748" height="30" alt="sf logo"/>
    </a>


    <a href="http://www.jetbrains.com/idea/">
        <img src="http://www.jetbrains.com/idea/opensource/img/banners/idea125x37_blue.gif" alt="The best Java IDE"
             border="0"/>
    </a>

    <a href="http://www.cenqua.com/">
        <img src="http://www.cenqua.com/images/cenqua_logo.gif" height="30" alt="cenqua logo"/>
    </a>

    <a href="http://atlassian.com/">
        <img src="http://atlassian.com/images/atlassian_logo_man2.gif" height="30" alt="atlassian logo"/>
    </a>
</footer>