
        <item name="Projects" >
            <item name="Overview of Projects" href="/projects-overview.html" collapse="true"/>
            <item name="Core" href="/multiproject/jcaptcha-core/index.html" collapse="true"/>
            <item name="Engine" href="/multiproject/jcaptcha-engine/index.html" collapse="true"/>
            <item name="Service" href="/multiproject/jcaptcha-service/index.html" collapse="true"/>
            <item name="Module base" href="/multiproject/jcaptcha-module-base/index.html" collapse="true"/>
            <item name="Module Struts" href="/multiproject/jcaptcha-module-struts/index.html" collapse="true"/>
            <item name="Module Filter" href="/multiproject/jcaptcha-module-filter/index.html" collapse="true"/>
            <item name="Module Roller" href="/multiproject/jcaptcha-module-roller/index.html" collapse="true"/>
        </item>
        <item name="Download">
            <item name="SourceForge Repository" href="http://sourceforge.net/project/showfiles.php?group_id=97877" collapse="true"/>
        </item>
        <item name="External links">
            <item name="Captcha" href="http://www.captcha.net" />
            <item name="Captcha@Wikipedia" href="http://en.wikipedia.org/wiki/Captcha" collapse="true"/>
            <item name="Captcha research paper" href="http://www.cs.cmu.edu/~biglou/captcha_cacm.pdf" collapse="true"/>
            <item name="Captcha presentation paper" href="http://www.cs.cmu.edu/~biglou/captcha_crypt.pdf" collapse="true"/>
        </item>

