        <links>
            <item name="Home" href="http://jcaptcha.sourceforge.net/"/>
            <item name="JCaptcha New Confluence" href="http://luminal.gotdns.com/confluence/"/>
            <item name="JCaptcha Old Wiki" href="http://jcaptcha.sourceforge.net/moniwiki/"/>
            <item name="JCaptcha@Sourceforge" href="http://sourceforge.net/projects/jcaptcha/"/>
            <item name="Demo" href="http://luminal.gotdns.com/demo/"/>
            <item name="Support" href="http://luminal.gotdns.com/jira/"/>
        </links>