        <links>
            <item name="Home" href="http://www.jcaptcha.net/"/>
            <item name="JCaptcha New Confluence" href="http://luminal.gotdns.com/confluence/"/>
            <item name="Support" href="http://luminal.gotdns.com/jira/"/>
            <item name="Demo" href="http://luminal.gotdns.com/struts-mailreader/"/>
            <item name="JCaptcha@Sourceforge" href="http://sourceforge.net/projects/jcaptcha/"/>
            <item name="JCaptcha Old Wiki" href="http://jcaptcha.sourceforge.net/moniwiki/"/>
        </links>
