        <links>
            <item name="Home" href="http://www.jcaptcha.net/"/>
            <item name="JCaptcha New Confluence" href="http://luminal.gotdns.com/confluence/"/>
            <item name="Support" href="http://luminal.gotdns.com/jira/"/>
            <item name="Demo" href="http://luminal.gotdns.com/struts-mailreader/"/>
            <item name="JCaptcha@Sourceforge" href="http://sourceforge.net/projects/jcaptcha/"/>
            <item name="JCaptcha Old Wiki" href="http://jcaptcha.sourceforge.net/moniwiki/"/>
        </links>


<footer>
    <a href="http://www.octo.com">
        <img src="http://www.octo.com/fr/images/logo.gif" height="30"  alt="octo technology logo" />
    </a>


    <a href="http://sourceforge.net/projects/jcaptcha">
        <img src="http://sourceforge.net/sflogo.php?group_id=72748" height="30" alt="sf logo"/>
    </a>


    <a href="http://www.jhlabs.com/">
        <img src="http://www.jhlabs.com/JHLabs.gif"  height="30" alt="jhlabs logo"/>
    </a>

    <a href="http://www.cenqua.com/clover/">
        <img src="http://www.cenqua.com/images/cenqua_logo.gif" height="30" alt="cenqua logo"/>
    </a>

    <a href="http://atlassian.com/">
        <img src="http://atlassian.com/images/atlassian_logo_man2.gif" height="30" alt="atlassian logo"/>
    </a>
</footer>