<menu name="Navigation" collapse="true">


    <item name="Documentation" href="http://forge.octo.com/jcaptcha/confluence/">
        <item name="How to.." href="http://forge.octo.com/jcaptcha/confluence/display/general/How+to"/>
        <item name="FAQ" href="http://forge.octo.com/jcaptcha/confluence/display/general/FAQ"/>

    </item>
    <item name="Issue tracker" href="http://forge.octo.com/jcaptcha/jira/"/>
    <item name="Mailing lists" href="http://sourceforge.net/mail/?group_id=97877"/>
    <item name="JCaptcha@Sourceforge.net" href="http://sourceforge.net/projects/jcaptcha/"/>
    <item name="Browse source" href="http://fisheye1.cenqua.com/viewrep/jcaptcha/jcaptcha"/>
</menu>